### PR TITLE
kyumhan.md

### PR DESCRIPTION
**Pull request by kyumhan**

### CODE REVIEW

**Review by robobenklein — CHANGES_REQUESTED** [review]
Erm, what's up with modifying the ports file?

**Comment by kyumhan** [comment]
oh I didn't mean to change the port files. All I did was add the kyumhan.md file.

**Comment by robobenklein** [comment]
Make sure that your git client supports symlinks, e.g. for windows: https://stackoverflow.com/a/42137273/2375851

**Comment by kyumhan** [comment]
does this mean I have to git clone again?

**Comment by robobenklein** [comment]
If you had to change that setting in git that's probably the easiest solution.

**Comment by kyumhan** [comment]
I added the option for symlink. Do I have to pull request again?

**Comment by robobenklein** [comment]
If you know how to cherry-pick a commit you could pick d9934c8af839a4742df3f9e6a74ea6c1f6c2f2ac, revert d97ef452936a802b012df9e2f62beda2fe783661 and force-push, otherwise it'll be easier just to make a new PR on a new branch.

**Comment by kyumhan** [comment]
it seems like when I git clone the repository, it modifies the port file.

**Pull request closed without merging**
