### PR TITLE
dscott57 intro 

### PR DESCRIPTION
**Pull request by DD-Scott**

### CODE REVIEW

**Comment by DD-Scott** [comment]
review-requested:@audris

**Comment by robobenklein** [comment]
No need to put your pubkey in the PR, it'll just pollute the directory.

If you've already added that key to your github account then I can pull your public keys from github automatically. (e.g. public keys are public, like mine at https://github.com/robobenklein.keys )

**Review by robobenklein — CHANGES_REQUESTED** [review]
I'll pull keys from github, no need for them tracked in git

**Comment by DD-Scott** [comment]
Removed .key

**Comment by DD-Scott** [comment]
@robobenklein I removed the key and re-published.

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
